Update glslopt to support language targets
The glslopt_initialize interface changed from bool to glsl glslopt_target in
28c35cc081744954ee9ae74c0a4e9b0336d76fe1

This broke glslopt like so:
```
Main.cpp:20:13: error: no matching function for call to 'glslopt_initialize'
        gContext = glslopt_initialize(false);
                   ^~~~~~~~~~~~~~~~~~
../../src/glsl/glsl_optimizer.h:45:14: note: candidate function not viable: no known conversion from 'bool' to
      'glslopt_target' for 1st argument
glslopt_ctx* glslopt_initialize (glslopt_target target);
```

This corrects that error and also introduces command-line options to
to choose the target language.